### ISSUE TITLE
how do you move Iotas from the paper wallet to another address or exchange?

### ISSUE THREAD

**Issue by seabirdsea** [arancauchi/IOTA-Paper-Wallet#10]
Can you please explain how to move Iotas from paper wallet to another address or exchange? Yes I do understand that the paper wallet is just for securing your seed but need to know how spend/move from wallet. thanks

**Comment by arancauchi** [comment]
All you need to do is use that seed that you inputted into the generator and put it into the IOTA wallet. That will retrieve your balance from the tangle, and you can spend it from there.

**Comment by seabirdsea** [comment]
ok, so if I understand I need to down load the IOTA wallet to my computer. I do not have the wallet down loaded to my computer at this time because of complaints I have read and the fact that I am not very tech savvy. im a tech idiot if I have to admit it. ; ) thanks for helping

**Comment by arancauchi** [comment]
Yep you are correct, just use a light wallet and enter your seed. It should work from there.

**Comment by seabirdsea** [comment]
I have more than one Iota paper wallet with different seeds can I put both different seeds into the wallet?

**Comment by arancauchi** [comment]
Yes you can use any seed in any wallet, it is simply a way to access funds.
