### ISSUE TITLE
Generating wrong addresses from seed

### ISSUE THREAD

**Issue by cvf23rf2fg2** [arancauchi/IOTA-Paper-Wallet#13]
Hi, 
version 1.3.2 is generating wrong addresses from a seed.
Not sure you are trying to scam people or if your Github account is hacked and replaced the generator for a malicious one.

**Comment by arancauchi** [comment]
Wow, what a super nice way to let me know that there is an issue. Thank you for calling me a scammer!
The iota.js library hasn't been updated in quite some time, I will take a look and see if I can get it inline with the current library. Maybe some slightly more respectful communication would go a lot further too.

**Comment by cvf23rf2fg2** [comment]
Hi,
I'm not calling you a scammer, I just don't know whats happening here.
Like i said, only version 1.3.2 is generating wrong addresses from a seed.

For example, if i use seed:
JUVNBQGTEBLIJSUIRNDNAXK9OUWQNFEIOP9UHTOMKISKVBXWBFNUZFBL9DPNNGCOWIKGYBNNZJJMXAUSP

Version 1.3.2 is generating this address:

Generated Address: 9PXFMCITBQXFUTKGJHCG9TL9ZMNCYEIYEOVWYPYTDCXXRNI9FMYNLJOBNGGGYB9EW9WQEDRDETDUJIWFLRVFODJ9RJ

And version 1.3.3 generate this (correct) address:

Generated Address: TLTZXDOUVRISEEUPDLMSAWQI9NRMRRSFKJFUEXAJCFGBSMHGJXXJPYBWODTABJXVPPUNAULOKKR9BOYECPLH9SCVPX

**Comment by arancauchi** [comment]
Thanks for this, I have updated to the 0.5.0 release of iota.js.
