### ISSUE TITLE
There should be minimum character limit for the seed.

### ISSUE THREAD

**Issue by devender-yadav** [arancauchi/IOTA-Paper-Wallet#2]
Currently, the paper wallet can also be created using 1 character only. 

There should be minimum characters limit as per the desktop wallet. **Desktop wallets(2.3.1) do not allow seeds less than 60 Characters.**

-Dev

**Comment by arancauchi** [comment]
Whilst you are correct that short seeds are far from desirable, seeds of 1 character are valid for IOTA, as the curl hashing function will pad out any input to a fixed number of words. It is not necessarily the purview of this application to describe what is or isn't a 'good' seed, simply only what is a 'valid' seed.
