### ISSUE TITLE
Discrete mode still says IOTA Paper Wallet on printed pages

### ISSUE THREAD

**Issue by sm1ddy** [arancauchi/IOTA-Paper-Wallet#5]
Hi Dev

Great wallet by the way.

I noticed that when printing in discrete mode, IOTA wallet is still mentioned on the top and bottom of the paper. That isn't very discrete. I think in the future you should test your software a bit more.

Just something to fix up.

Cheers

**Comment by arancauchi** [comment]
Fixed. Recommend you learn how to dev ;)
