### ISSUE TITLE
What does Enter Security make?

### ISSUE THREAD

**Issue by turunut** [arancauchi/IOTA-Paper-Wallet#6]
Hello,

First of all i want to thank you for this project, it's very usefull.

I only have one question about the option 'Enter Security' in Advance menu.
What does it do?

Thank you very much for all.

**Comment by arancauchi** [comment]
Security refers to the security level of seeds that are generated:
https://learn.iota.org/tutorial/generating-addresses-learn-the-basics for more info

**Comment by turunut** [comment]
Wow thank's, I didn't know that.
